export const AntdTheme = {
	token: {
		colorPrimary: "#ff7506",
		colorBgContainer: "rgba(47, 47, 65, 0.7)",
		colorBgElevated: "rgba(47, 47, 65)",
		colorBorder: "rgb(67, 67, 79)",
		colorBorderSecondary: "rgb(67, 67, 79)",
		colorText: "#fff",
		colorTextPlaceholder: "rgb(166, 166, 166, 0.8);",
		colorTextDisabled: "#888",
	},
	components: {
		Select: {
			colorBgContainer: "rgba(47, 47, 65, 0.7)",
			colorTextDisabled: "#ff7506",
			colorText: "#bbb",
		},
		Input: {},
		DatePicker: {
			colorIcon: "#ff7506",
			colorIconHover: "#fff",
			colorTextDisabled: "#ff7506",
		},
		Checkbox: {
			// colorBgContainer: "#fff",
			colorBorder: "#347aff",
			fontSize: 16,
		},
		Radio: {
			colorBorder: "#ff7506",
			borderRadius: 10,
		},
		Menu: {
			radiusItem: 0,
			itemMarginInline: 0,
			colorItemText: "#fff",
			colorItemBg: "#020220",
			colorItemTextHover: "#ff7506",
			colorItemBgHover: "#2c2c2c",
			colorItemTextSelected: "#ff7506",
			colorItemBgSelected: "#1e1e2e",
		},
		Table: {
			colorText: "#fff",
			colorTextHeading: "#ffac69",
			colorBgContainer: "rgba(47, 47, 65, 0.7)",
			colorSplit: "#53535371",
			fontSize: 14,
			lineHeight: 0.8,
		},
		Pagination: {
			colorPrimary: "#f5f5ff",
			colorPrimaryBorder: "#000",
			colorText: "#f5f5ff",
			colorTextDisabled: "#f5f5ff",
			colorBgContainer: "#ff7506",
			colorPrimaryHover: "#fefefe",
			colorBgTextHover: "#686868",
			borderRadius: 20,
		},
	},
};
